### ISSUE TITLE
Release of the fixes for linux

### ISSUE THREAD

**Issue by jankatins** [printfn/bp#4]
I use the provided release binaries to install bp (via some zinit install magic) and that worked nicely on mac but now on linux I need to install via `cargo install --git https://github.com/printfn/bp` because the latest fixes for linux from #3 are missing. Would it be possible to cut a release with these fixes included?

**Comment by printfn** [comment]
Thanks for reminding me, I've now released it to crates.io.

**Comment by jankatins** [comment]
Any chance to also add the assets to https://github.com/printfn/bp/releases/tag/v0.1.5? I use zinit to download the precompiled binaries...

**Comment by printfn** [comment]
Done
